In [2]:
import torch

In [10]:
a = torch.rand((4,3,2,2,2))
print(a)

tensor([[[[[6.8437e-01, 6.6645e-01],
           [6.1420e-01, 9.7138e-01]],

          [[9.0988e-03, 2.4010e-01],
           [3.0941e-01, 6.4253e-01]]],


         [[[8.1618e-01, 3.9186e-01],
           [4.6245e-01, 1.0204e-01]],

          [[7.0889e-01, 6.1421e-01],
           [7.7820e-04, 1.0868e-01]]],


         [[[8.9628e-01, 4.3327e-01],
           [7.9367e-01, 4.3877e-01]],

          [[1.2066e-01, 5.4817e-01],
           [1.3070e-01, 8.5311e-01]]]],



        [[[[4.3125e-01, 4.2810e-01],
           [4.6653e-01, 4.0986e-01]],

          [[3.5966e-01, 8.9811e-01],
           [9.7829e-01, 8.2743e-01]]],


         [[[9.9206e-01, 5.6373e-01],
           [3.4476e-01, 7.7663e-01]],

          [[5.1998e-01, 8.3694e-02],
           [7.9849e-01, 8.6609e-01]]],


         [[[4.1624e-01, 4.0059e-01],
           [8.1382e-01, 8.1350e-01]],

          [[8.1746e-01, 6.4996e-01],
           [2.7230e-01, 3.6231e-01]]]],



        [[[[5.6656e-01, 6.0794e-01],
           [8.9278e-01, 4.0905e-01]

In [12]:
print(a[:,1,...] == a[:,1])
# print(a[:,1,:])
# print(a[:,1])


tensor([[[[True, True],
          [True, True]],

         [[True, True],
          [True, True]]],


        [[[True, True],
          [True, True]],

         [[True, True],
          [True, True]]],


        [[[True, True],
          [True, True]],

         [[True, True],
          [True, True]]],


        [[[True, True],
          [True, True]],

         [[True, True],
          [True, True]]]])


In [16]:
size_in = 200
size_out = 20



weights = torch.empty(
                (size_in, size_out), # self.nb_units_by_layer[l : l + 2], @@@@@@@@@@@@@@@@@@
            )

nb_units_by_layer = (700, 200, 20)


l = 1

weignt = torch.empty(
                nb_units_by_layer[l : l + 2],
            )

print(weights.shape==weignt.shape)

print(weights.shape)
print(weignt.shape)

True
torch.Size([200, 20])
torch.Size([200, 20])


In [46]:


x = torch.rand((3,4,5))
weights = torch.rand((5,6))

weighted_spikes_l1 = torch.einsum(
                    # [b]atches, [t]ime, [i]nput units, [h]idden units
                    "bti,ih->bth",
                    x, weights,
                )

linear = torch.nn.functional.linear(x,weights.T)


#print(f'weighted_spikes_l1 : {weighted_spikes_l1}\n linear : {linear}')
print((weighted_spikes_l1).allclose(linear))

print(torch.equal(weighted_spikes_l1, linear))

print((weighted_spikes_l1.float()==linear.float()))

print(f'weighted_spikes_l1.shape: {weighted_spikes_l1.shape}\n linear.shape: {linear.shape}')




True
False
tensor([[[ True,  True,  True,  True,  True,  True],
         [ True,  True,  True, False,  True,  True],
         [ True,  True,  True,  True,  True,  True],
         [ True, False,  True,  True,  True, False]],

        [[ True,  True,  True,  True, False,  True],
         [ True,  True,  True,  True,  True,  True],
         [ True,  True,  True, False,  True,  True],
         [ True,  True, False,  True, False,  True]],

        [[ True, False,  True,  True, False,  True],
         [ True, False,  True,  True, False, False],
         [ True, False, False,  True,  True,  True],
         [False,  True,  True,  True,  True,  True]]])
weighted_spikes_l1.shape: torch.Size([3, 4, 6])
 linear.shape: torch.Size([3, 4, 6])


In [1]:
import torch

x = torch.rand((3,4,5))

linear_layer = torch.nn.Linear(in_features=5,out_features=6,bias=False, device='cpu')

weights2 = linear_layer.weight
print(weights2.shape)

output_manual = torch.einsum(
                    # [b]atches, [t]ime, [i]nput units, [h]idden units
                    "bti,ih->bth",
                    x, weights2.T,
                )

lin = linear_layer(x)

print(torch.allclose(lin,output_manual))
print(f'lin.shape: {lin.shape}')


torch.Size([6, 5])
True
lin.shape: torch.Size([3, 4, 6])


In [62]:
from pyexpat import model
from turtle import forward


# def weight_reset(m):
#     if isinstance(m, torch.nn.Conv2d) or isinstance(m, torch.nn.Linear):
#         m.reset_parameters()
#         print(f'worked!')

# model = torch.nn.Sequential(
#     torch.nn.Conv2d(3, 6, 3, 1, 1),
#     torch.nn.ReLU(),
#     torch.nn.Linear(20, 3)
# )

class myModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = torch.nn.Sequential(
    torch.nn.Conv2d(3, 6, 3, 1, 1),
    torch.nn.ReLU(),
    torch.nn.Linear(20, 3)   
)
        self.apply(self.weight_reset)
        
    def forward(self,x):
        return x

    def weight_reset(self,m):
        if isinstance(m, torch.nn.Conv2d) or isinstance(m, torch.nn.Linear):
            m.reset_parameters()
            print(f'worked!')
    
model = myModel()

#model.apply(weight_reset)

worked!
worked!


For the TwoCompartmentSpikingNetwork

In [65]:
size_in = 200
size_out = 20



weights = torch.empty(
                (size_in, size_out, 2), # self.nb_units_by_layer[l : l + 2], @@@@@@@@@@@@@@@@@@
            )

nb_units_by_layer = (700, 200, 20)


l = 1

weignt = torch.empty(
                (*nb_units_by_layer[l : l + 2],2)
            )

print(weights.shape==weignt.shape)

print(weights.shape)
print(weignt.shape)

True
torch.Size([200, 20, 2])
torch.Size([200, 20, 2])


In [67]:


x = torch.rand((3,4,5))
weights = torch.rand((5,6,7))

weighted_spikes_l1 = torch.einsum(
                # [b]atches, [t]ime, [i]nput units, [h]idden units, [c]ompartments
                "bti,ihc->bthc",
                (x, weights),
            )

x2= torch.rand((3,4, 5))
linear = torch.nn.functional.linear(x, weights)


#print(f'weighted_spikes_l1 : {weighted_spikes_l1}\n linear : {linear}')
print((weighted_spikes_l1).allclose(linear))

print(torch.equal(weighted_spikes_l1, linear))

print((weighted_spikes_l1.float()==linear.float()))

print(f'weighted_spikes_l1.shape: {weighted_spikes_l1.shape}\n linear.shape: {linear.shape}')

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 3D

In [76]:
from torch import nn
import math

class Linear3d(nn.Module):
    """ Custom Linear layer with 3d weights """
    def __init__(self, in_features: int, out_features: int, third_dim: int, bias: bool = False,
                 device=None, dtype=None): #bias=False
        super(Linear3d, self).__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.third_dim = third_dim
        self.weight = nn.Parameter(torch.empty((in_features, out_features, third_dim), device=device, dtype=dtype))
        if bias:
            self.bias = nn.Parameter(torch.empty((out_features, third_dim), device=device, dtype=dtype))
        else:
            self.register_parameter('bias', None)
        self.reset_parameters()

    def forward(self, x : torch.Tensor):
        # ..., [i]nput features, [o]utput features, [t]hird dimension
        return torch.einsum("...i,iot->...ot", (x, self.weight))
    
    def reset_parameters(self) -> None:
        # Setting a=sqrt(5) in kaiming_uniform is the same as initializing with
        # uniform(-1/sqrt(in_features), 1/sqrt(in_features)). For details, see
        # https://github.com/pytorch/pytorch/issues/57109
        nn.init.kaiming_uniform_(self.weight, a=math.sqrt(5))
        if self.bias is not None:
            fan_in, _ = nn.init._calculate_fan_in_and_fan_out(self.weight)
            bound = 1 / math.sqrt(fan_in) if fan_in > 0 else 0
            nn.init.uniform_(self.bias, -bound, bound)
            
    def extra_repr(self) -> str:
        return 'in_features={}, out_features={}, third_dim={}, bias={}'.format(
            self.in_features, self.out_features, self.third_dim, self.bias is not None
        )

In [77]:
b = 3
t = 4
i = 5
h = 6
c = 2

bti = torch.rand((b,t,i))

randweights = torch.rand((i,h,c))
print(f'randweights.shape : {randweights.shape}')

linear3dLayer = Linear3d(i,h,c)
weights = linear3dLayer.weight
print(f'weights.shape : {weights.shape}')

output1 = torch.einsum(
                # [b]atches, [t]ime, [i]nput units, [h]idden units, [c]ompartments
                "bti,ihc->bthc",
                (bti, randweights),
            )
print(f'output1.shape : {output1.shape}')

output2 = torch.einsum(
                # [b]atches, [t]ime, [i]nput units, [h]idden units, [c]ompartments
                "bti,ihc->bthc",
                (bti, weights),
            )
print(f'output2.shape : {output2.shape}')

output3 = linear3dLayer(bti)
print(f'output3.shape : {output3.shape}')


print(f'torch.allclose(output2,output3) : {torch.allclose(output2,output3)}')

randweights.shape : torch.Size([5, 6, 2])
weights.shape : torch.Size([5, 6, 2])
output1.shape : torch.Size([3, 4, 6, 2])
output2.shape : torch.Size([3, 4, 6, 2])
output3.shape : torch.Size([3, 4, 6, 2])
torch.allclose(output2,output3) : True


# Class Inheritance

In [49]:
from torch import nn

class Neuron1(nn.Module):
    def __init__(self, nb_units) -> None:
        super(Neuron1, self).__init__()
    
    def forward(self, x):
        print(f'1 * {x}')

class Neuron2(nn.Module):
    def __init__(self, nb_units) -> None:
        super(Neuron2, self).__init__()
    
    def forward(self, x):
        print(f'2 * {x}')

class ParentModel(nn.Module):
    def __init__(self, moduleclass, nb_units) -> None:
        super(ParentModel, self).__init__()
        self.layer = moduleclass(nb_units)
    
    def forward(self, x):
        return self.layer(x)
        
class ChildrenModel1(ParentModel):
    def __init__(self, nb_units) -> None:
        super(ChildrenModel1, self).__init__(Neuron1, nb_units)
    
    def forward(self, x):
        return self.layer(x)

class GrandChild(ChildrenModel1):
    def __init__(self) -> None:
        super(GrandChild, self).__init__(4)

In [53]:

model = ParentModel(Neuron2,4)
print(model('test'))

child = ChildrenModel1(4)
print(child('should be 1'))

grandchild = GrandChild()
print(grandchild('test'))

2 * test
None
1 * should be 1
None
1 * test
None


In [17]:
import itertools


dictionnary = {'lr' : [0.001, 0.002, 0.003],
                       'bs' : [1, 2, 3],
                       'hidden' : [10, 20, 30]
        }
print(dictionnary.values())
unpacked = [*dictionnary.values()]
print(unpacked)

prod = itertools.product(*dictionnary.values())
#print(*prod)


for lr, bs, hidden in [*prod]:
    print(lr,bs,hidden)

dict_values([[0.001, 0.002, 0.003], [1, 2, 3], [10, 20, 30]])
[[0.001, 0.002, 0.003], [1, 2, 3], [10, 20, 30]]
0.001 1 10
0.001 1 20
0.001 1 30
0.001 2 10
0.001 2 20
0.001 2 30
0.001 3 10
0.001 3 20
0.001 3 30
0.002 1 10
0.002 1 20
0.002 1 30
0.002 2 10
0.002 2 20
0.002 2 30
0.002 3 10
0.002 3 20
0.002 3 30
0.003 1 10
0.003 1 20
0.003 1 30
0.003 2 10
0.003 2 20
0.003 2 30
0.003 3 10
0.003 3 20
0.003 3 30
