In [2]:
import torch

In [10]:
a = torch.rand((4,3,2,2,2))
print(a)

tensor([[[[[6.8437e-01, 6.6645e-01],
           [6.1420e-01, 9.7138e-01]],

          [[9.0988e-03, 2.4010e-01],
           [3.0941e-01, 6.4253e-01]]],


         [[[8.1618e-01, 3.9186e-01],
           [4.6245e-01, 1.0204e-01]],

          [[7.0889e-01, 6.1421e-01],
           [7.7820e-04, 1.0868e-01]]],


         [[[8.9628e-01, 4.3327e-01],
           [7.9367e-01, 4.3877e-01]],

          [[1.2066e-01, 5.4817e-01],
           [1.3070e-01, 8.5311e-01]]]],



        [[[[4.3125e-01, 4.2810e-01],
           [4.6653e-01, 4.0986e-01]],

          [[3.5966e-01, 8.9811e-01],
           [9.7829e-01, 8.2743e-01]]],


         [[[9.9206e-01, 5.6373e-01],
           [3.4476e-01, 7.7663e-01]],

          [[5.1998e-01, 8.3694e-02],
           [7.9849e-01, 8.6609e-01]]],


         [[[4.1624e-01, 4.0059e-01],
           [8.1382e-01, 8.1350e-01]],

          [[8.1746e-01, 6.4996e-01],
           [2.7230e-01, 3.6231e-01]]]],



        [[[[5.6656e-01, 6.0794e-01],
           [8.9278e-01, 4.0905e-01]

In [12]:
print(a[:,1,...] == a[:,1])
# print(a[:,1,:])
# print(a[:,1])


tensor([[[[True, True],
          [True, True]],

         [[True, True],
          [True, True]]],


        [[[True, True],
          [True, True]],

         [[True, True],
          [True, True]]],


        [[[True, True],
          [True, True]],

         [[True, True],
          [True, True]]],


        [[[True, True],
          [True, True]],

         [[True, True],
          [True, True]]]])


In [16]:
size_in = 200
size_out = 20



weights = torch.empty(
                (size_in, size_out), # self.nb_units_by_layer[l : l + 2], @@@@@@@@@@@@@@@@@@
            )

nb_units_by_layer = (700, 200, 20)


l = 1

weignt = torch.empty(
                nb_units_by_layer[l : l + 2],
            )

print(weights.shape==weignt.shape)

print(weights.shape)
print(weignt.shape)

True
torch.Size([200, 20])
torch.Size([200, 20])


In [46]:


x = torch.rand((3,4,5))
weights = torch.rand((5,6))

weighted_spikes_l1 = torch.einsum(
                    # [b]atches, [t]ime, [i]nput units, [h]idden units
                    "bti,ih->bth",
                    x, weights,
                )

linear = torch.nn.functional.linear(x,weights.T)


#print(f'weighted_spikes_l1 : {weighted_spikes_l1}\n linear : {linear}')
print((weighted_spikes_l1).allclose(linear))

print(torch.equal(weighted_spikes_l1, linear))

print((weighted_spikes_l1.float()==linear.float()))

print(f'weighted_spikes_l1.shape: {weighted_spikes_l1.shape}\n linear.shape: {linear.shape}')




True
False
tensor([[[ True,  True,  True,  True,  True,  True],
         [ True,  True,  True, False,  True,  True],
         [ True,  True,  True,  True,  True,  True],
         [ True, False,  True,  True,  True, False]],

        [[ True,  True,  True,  True, False,  True],
         [ True,  True,  True,  True,  True,  True],
         [ True,  True,  True, False,  True,  True],
         [ True,  True, False,  True, False,  True]],

        [[ True, False,  True,  True, False,  True],
         [ True, False,  True,  True, False, False],
         [ True, False, False,  True,  True,  True],
         [False,  True,  True,  True,  True,  True]]])
weighted_spikes_l1.shape: torch.Size([3, 4, 6])
 linear.shape: torch.Size([3, 4, 6])


In [50]:
# x = x.view(-1, 5)
# b_size = x.size(0)
# #x = linear(x)
# x = x.view(b_size, -1, 1)

linear_layer = torch.nn.Linear(in_features=5,out_features=6,bias=False, device='cpu')

weights2 = linear_layer.weight
print(weights2.shape)
output_manual = torch.einsum(
                    # [b]atches, [t]ime, [i]nput units, [h]idden units
                    "bti,ih->bth",
                    x, weights2.T,
                )

lin = linear_layer(x)

print(torch.allclose(lin,output_manual))
print(f'lin.shape: {lin.shape}')


6
True
lin.shape: torch.Size([3, 4, 6])
